# add_thumbnails.py
"""Add a premium thumbnail (256x256 PNG) to each .mcpack in the output folder.
The thumbnail image is generated by Antigravity and stored at
`assets/default_thumbnail.jpg` in the repository.
The script extracts each .mcpack, copies the thumbnail as `thumbnail.png`
and re‑zips the pack.
"""
import os, shutil, zipfile, tempfile

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
OUTPUT_DIR = os.path.join(BASE_DIR, 'output')
THUMB_PATH = os.path.join(BASE_DIR, 'assets', 'default_thumbnail_1782575116746.jpg')

if not os.path.isfile(THUMB_PATH):
    raise FileNotFoundError(f"Thumbnail not found: {THUMB_PATH}")

def add_thumbnail(mcpack_path):
    with tempfile.TemporaryDirectory() as tmp:
        with zipfile.ZipFile(mcpack_path, 'r') as zip_ref:
            zip_ref.extractall(tmp)
        # copy thumbnail as thumbnail.png (required name by Marketplace)
        shutil.copy2(THUMB_PATH, os.path.join(tmp, 'thumbnail.png'))
        # re‑zip
        new_path = mcpack_path + '.new'
        with zipfile.ZipFile(new_path, 'w', zipfile.ZIP_DEFLATED) as zip_out:
            for root, _, files in os.walk(tmp):
                for f in files:
                    abs_path = os.path.join(root, f)
                    rel_path = os.path.relpath(abs_path, tmp)
                    zip_out.write(abs_path, rel_path)
        shutil.move(new_path, mcpack_path)
        print(f"Thumbnail added to {os.path.basename(mcpack_path)}")

if __name__ == '__main__':
    for fname in os.listdir(OUTPUT_DIR):
        if fname.lower().endswith('.mcpack'):
            add_thumbnail(os.path.join(OUTPUT_DIR, fname))
